// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAA3ROsFLzd9pjRnb009tYvh-dVIXo1vI',
    appId: '1:553634347311:web:5dfbe576cda06cdd2789da',
    messagingSenderId: '553634347311',
    projectId: 'fleetos-push',
    authDomain: 'fleetos-push.firebaseapp.com',
    storageBucket: 'fleetos-push.firebasestorage.app',
    measurementId: 'G-63W5K7CQWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxWEIm3U6rZ9Jcjp9kjZBrU1XHIbkLfuE',
    appId: '1:553634347311:android:51ac4cc9b26a718b2789da',
    messagingSenderId: '553634347311',
    projectId: 'fleetos-push',
    storageBucket: 'fleetos-push.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRKSRhbNyhqOAgV70kyLIZ5m2UKJ5ZKps',
    appId: '1:553634347311:ios:684af3359551e6062789da',
    messagingSenderId: '553634347311',
    projectId: 'fleetos-push',
    storageBucket: 'fleetos-push.firebasestorage.app',
    iosBundleId: 'com.example.axionTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRKSRhbNyhqOAgV70kyLIZ5m2UKJ5ZKps',
    appId: '1:553634347311:ios:684af3359551e6062789da',
    messagingSenderId: '553634347311',
    projectId: 'fleetos-push',
    storageBucket: 'fleetos-push.firebasestorage.app',
    iosBundleId: 'com.example.axionTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAA3ROsFLzd9pjRnb009tYvh-dVIXo1vI',
    appId: '1:553634347311:web:f4bafde1f3d8d6112789da',
    messagingSenderId: '553634347311',
    projectId: 'fleetos-push',
    authDomain: 'fleetos-push.firebaseapp.com',
    storageBucket: 'fleetos-push.firebasestorage.app',
    measurementId: 'G-HGMN9MRNY1',
  );
}
